# Generated by Django 3.0.8 on 2020-08-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200803_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='answer_status',
        ),
        migrations.AddField(
            model_name='post',
            name='tit',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
